import 'package:flutter/foundation.dart';
import 'package:go_router/go_router.dart';
import 'package:material_ui/material_ui.dart';

import 'analytics_observer.dart';
import 'route_guard.dart';

// ---------------------------------------------------------------------------
// RouteArchitect – Zero-Friction Static Builder
// ---------------------------------------------------------------------------

/// The single entry-point for creating a production-ready, enterprise-grade
/// [GoRouter] instance.
///
/// [RouteArchitect.create] hides all `go_router` boilerplate behind a clean,
/// declarative API. The developer does **not** need to understand `go_router`
/// internals – just define routes, guards, and an optional error screen.
///
/// ## Features
/// - **Guard Pipeline** – async Chain of Responsibility via [RouteGuard].
/// - **Deep Link Safety** – broken deep links are intercepted, logged, and
///   gracefully handled via [fallbackLocation] or a customisable error screen.
/// - **Analytics Integration** – plug any number of [RouteAnalyticsObserver]s.
/// - **Auth Reactivity** – via [refreshListenable] (state-management agnostic).
/// - **Zero Crashes** – the error builder guarantees the app never crashes
///   due to an unknown route.
///
/// ## Quick Start
/// ```dart
/// final router = RouteArchitect.create(
///   routes: $appRoutes,                          // from go_router_builder
///   guards: [AuthGuard(auth), RoleGuard(auth)],
///   refreshListenable: authNotifier,
///   initialLocation: '/home',
///   fallbackLocation: '/',                       // broken deep links → here
///   observers: [DebugRouteObserver()],
/// );
///
/// // Then in MaterialApp:
/// MaterialApp.router(routerConfig: router);
/// ```
///
/// ## Advanced Configuration
/// ```dart
/// final router = RouteArchitect.create(
///   routes: $appRoutes,
///   guards: [AuthGuard(auth), SubscriptionGuard(billing)],
///   refreshListenable: Listenable.merge([authNotifier, billingNotifier]),
///   initialLocation: '/dashboard',
///   fallbackLocation: '/home',
///   errorScreenBuilder: (context, state) => const CustomNotFoundScreen(),
///   observers: [FirebaseRouteObserver(), AmplitudeRouteObserver()],
///   debugLogDiagnostics: kDebugMode,
///   restorationScopeId: 'root-router',
///   redirectLimit: 10,
/// );
/// ```
abstract final class RouteArchitect {
  RouteArchitect._();

  /// Creates and returns a fully configured [GoRouter] instance.
  ///
  /// ### Parameters
  ///
  /// - **[routes]** *(required)* – The route tree. Typically `$appRoutes`
  ///   generated by `go_router_builder`, or a manually assembled list of
  ///   [GoRoute] / [ShellRoute] / [StatefulShellRoute].
  ///
  /// - **[guards]** – An ordered list of [RouteGuard]s forming the redirect
  ///   pipeline. Guards execute sequentially; the first non-null redirect
  ///   wins. Supports `FutureOr<String?>` for async checks.
  ///
  /// - **[refreshListenable]** – A [Listenable] that triggers re-evaluation
  ///   of the guard pipeline whenever it notifies. Use
  ///   `ListenableNotifier` (mixin) or `StreamListenable` (class) from this
  ///   package to bridge any state management solution.
  ///
  /// - **[initialLocation]** – The starting route path. Defaults to `'/'`.
  ///
  /// - **[fallbackLocation]** – Where to redirect when a deep link targets
  ///   an unknown route. If provided, broken deep links are silently
  ///   redirected here instead of showing an error screen. Route errors are
  ///   still logged via [observers]. Defaults to `null` (show error screen).
  ///
  /// - **[errorScreenBuilder]** – Custom widget builder for the error /
  ///   404 page. If omitted, a polished built-in error page is displayed.
  ///   This is only used when [fallbackLocation] is `null`.
  ///
  /// - **[observers]** – Analytics observers attached to the root navigator.
  ///   `onRouteError` is called when [fallbackLocation] handles an error.
  ///
  /// - **[debugLogDiagnostics]** – Enables `go_router`'s verbose logging.
  ///   Defaults to `false`.
  ///
  /// - **[restorationScopeId]** – Enables state restoration for the router.
  ///
  /// - **[redirectLimit]** – Maximum consecutive redirects before `go_router`
  ///   throws. Defaults to `20`. Lower in tests to catch redirect loops.
  static GoRouter create({
    required List<RouteBase> routes,
    List<RouteGuard> guards = const [],
    List<RouteAnalyticsObserver> observers = const [],
    Listenable? refreshListenable,
    String initialLocation = '/',
    String? fallbackLocation,
    Widget Function(BuildContext context, GoRouterState state)?
        errorScreenBuilder,
    bool debugLogDiagnostics = false,
    String? restorationScopeId,
    int redirectLimit = 20,
  }) {
    assert(routes.isNotEmpty,
        'RouteArchitect: You must provide at least one route.');

    // go_router enforces: only ONE of onException, errorBuilder, or
    // errorPageBuilder may be provided. We branch based on whether a
    // fallbackLocation was configured.

    final effectiveErrorBuilder = errorScreenBuilder ??
        (BuildContext context, GoRouterState state) => _DefaultRouteErrorScreen(
              error: state.error,
              initialLocation: initialLocation,
            );

    if (fallbackLocation != null) {
      // ── Fallback-redirect strategy ──────────────────────────────────────
      // Broken deep links are silently redirected to [fallbackLocation].
      return GoRouter(
        routes: routes,
        initialLocation: initialLocation,
        refreshListenable: refreshListenable,
        observers: observers,
        debugLogDiagnostics: debugLogDiagnostics,
        restorationScopeId: restorationScopeId,
        redirectLimit: redirectLimit,
        redirect: guards.isEmpty
            ? null
            : (context, state) => GuardPipeline.run(guards, context, state),
        onException: (context, state, router) {
          for (final observer in observers) {
            observer.onRouteError(state.uri.toString(), state.error);
          }
          router.go(fallbackLocation);
        },
      );
    }

    // ── Error-screen strategy ───────────────────────────────────────────
    // Unknown routes show [errorScreenBuilder] or the built-in 404 page.
    return GoRouter(
      routes: routes,
      initialLocation: initialLocation,
      refreshListenable: refreshListenable,
      observers: observers,
      debugLogDiagnostics: debugLogDiagnostics,
      restorationScopeId: restorationScopeId,
      redirectLimit: redirectLimit,
      redirect: guards.isEmpty
          ? null
          : (context, state) => GuardPipeline.run(guards, context, state),
      errorBuilder: effectiveErrorBuilder,
    );
  }
}

// ---------------------------------------------------------------------------
// Default Error Screen
// ---------------------------------------------------------------------------

/// Built-in 404 / route error page displayed when no [errorScreenBuilder]
/// is provided and [fallbackLocation] is null.
///
/// Features:
/// - Clean, minimal Material Design layout.
/// - Displays the error message in debug mode for diagnostics.
/// - "Go to Start" button to recover gracefully.
class _DefaultRouteErrorScreen extends StatelessWidget {
  const _DefaultRouteErrorScreen({this.error, required this.initialLocation});

  final Exception? error;
  final String initialLocation;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Page Not Found'),
        centerTitle: true,
      ),
      body: SafeArea(
        child: Center(
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 32),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(
                  Icons.explore_off_outlined,
                  size: 80,
                  color: theme.colorScheme.outline,
                ),
                const SizedBox(height: 24),
                Text(
                  '404',
                  style: theme.textTheme.displaySmall?.copyWith(
                    fontWeight: FontWeight.bold,
                    color: theme.colorScheme.onSurface,
                  ),
                ),
                const SizedBox(height: 8),
                Text(
                  'The page you are looking for does not exist.',
                  textAlign: TextAlign.center,
                  style: theme.textTheme.bodyLarge?.copyWith(
                    color: theme.colorScheme.onSurfaceVariant,
                  ),
                ),
                if (kDebugMode && error != null) ...[
                  const SizedBox(height: 12),
                  Text(
                    error.toString(),
                    textAlign: TextAlign.center,
                    style: theme.textTheme.bodySmall?.copyWith(
                      color: theme.colorScheme.error,
                    ),
                    maxLines: 3,
                    overflow: TextOverflow.ellipsis,
                  ),
                ],
                const SizedBox(height: 32),
                FilledButton.icon(
                  icon: const Icon(Icons.home_outlined),
                  label: const Text('Go to Start'),
                  onPressed: () => context.go(initialLocation),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
